@startuml
'https://plantuml.com/sequence-diagram
autonumber

标准_定时任务->标准_定时任务:凌晨1点发起
标准_定时任务->标准区_基础库tidb:根据优先级，配置状态获取要拉取数据的配置
标准区_基础库tidb->标准_定时任务:获取拉取数据配置
loop #blue 拉取数据配置循环
标准_定时任务 -> p5mcp:根据传入参数获取 1000条数据,总数量
p5mcp -> p8_sync:p5通过p4注册中心调用sync\np 获取拉取的 1000条数据
p8_sync -> p5mcp:返回获取数据
p5mcp -> 标准_定时任务:返回获取数据
    alt#Gold #LightBlue 总数>100000
        标准_定时任务 -> 标准_定时任务: 更新拉取配置的状态:失败，总数超过 100000
    else  #Pink 总数<100000
        autonumber 9.1
        标准_定时任务 -> 标准_定时任务: 根据配置把返回的总数更新到配置表
        标准_定时任务 -> 标准_定时任务: 更新数据配置的拉取最后一个数据的值,更新状态：拉取中
        loop #green 单条配置循环拉取数据
             标准_定时任务 -> p5mcp:根据传入参数和同步的位置数据值获取下1000条数据
             p5mcp -> p8_sync:p5通过p4注册中心调用sync\np 获取拉取的 1000条数据
             p8_sync -> p5mcp:返回获取数据
             p5mcp -> 标准_定时任务:返回获取数据
             标准_定时任务 -> 标准_定时任务: 根据配置把返回的 1000写入目标Tidb库
             标准_定时任务 -> 标准_定时任务: 更新数据配置的拉取最后一个数据的值
             alt 查询返回的数据<1000
               标准_定时任务 -> 标准_定时任务:退出循环处理
             end
             alt 当前时间超过凌晨5点
               标准_定时任务 -> 标准_定时任务:退出定时任务
             end
        end
        标准_定时任务 -> 标准_定时任务:更新数据配置状态：拉取完成
    end

end
@enduml