@startuml
'https://plantuml.com/sequence-diagram
autonumber
标准_定时任务->标准_定时任务:凌晨1点发起
标准_定时任务->标准区_基础库tidb:查询比对配置
标准区_基础库tidb->标准_定时任务:获取同步配置
loop 比对配置循环
标准_定时任务 -> 标准区数据库: 获取标准区的源库，目标库的数据总量
标准_定时任务 -> p5mcp:获取自用区\n 源库，目标库的数据总量
p5mcp -> p8_sync:p5通过p4注册中心调用sync\np 获取源库，目标库的数据总量
p8_sync -> p5mcp:返回获取数据
p5mcp -> 标准_定时任务:返回获取数据
标准_定时任务 -> 标准_定时任务: 根据第4步，第8步进行数据比对
标准_定时任务 -> 标准区_基础库tidb: 比对结果入库
end
@enduml