@startuml
'https://plantuml.com/sequence-diagram
autonumber
标准区_定时任务工程->标准区_基础数据库:同步失败记录失败信息
标准区_定时任务工程-[#red]>标准区_kafka:发送失败记录信息到kafka
标准区_kafka-->标准区_定时任务工程:消费失败的记录消息
标准区_定时任务工程->p5mcp:p5透传到自用区
p5mcp->NPSP:通过p4调用N-PSP的TA238RH02
@enduml